In [1]:
import numpy as np

In [17]:
a = np.arange(1,16,1).reshape(3,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [15]:
b = np.arange(1,16)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [16]:
b*10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150])

In [26]:
from IPython import display
from PIL import Image

In [27]:
im = Image.open('img.png')

In [36]:
array = np.array(im)
print(array.shape)
array

(239, 346, 4)


array([[[171, 171, 171, 255],
        [127, 128, 129, 255],
        [ 69,  72,  74, 255],
        ...,
        [ 60,  63,  65, 255],
        [ 60,  63,  65, 255],
        [ 60,  63,  65, 255]],

       [[173, 173, 173, 255],
        [173, 173, 173, 255],
        [167, 167, 168, 255],
        ...,
        [ 60,  63,  65, 255],
        [ 60,  63,  65, 255],
        [ 60,  63,  65, 255]],

       [[173, 173, 173, 255],
        [173, 173, 173, 255],
        [173, 173, 173, 255],
        ...,
        [ 60,  63,  65, 255],
        [ 60,  63,  65, 255],
        [ 60,  63,  65, 255]],

       ...,

       [[ 60,  63,  65, 255],
        [ 60,  63,  65, 255],
        [ 60,  63,  65, 255],
        ...,
        [ 60,  63,  65, 255],
        [ 60,  63,  65, 255],
        [ 60,  63,  65, 255]],

       [[ 60,  63,  65, 255],
        [ 60,  63,  65, 255],
        [ 60,  63,  65, 255],
        ...,
        [ 60,  63,  65, 255],
        [ 60,  63,  65, 255],
        [ 60,  63,  65, 255]],

       [[ 60